services:
  finx-loan-officer:
    build: ./finx-loan-officer-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  finx-customer:
    build: ./finx-customer-loan-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_FORMIO_API_BASE_URL=http://3.110.81.211
      - REACT_APP_FORMIO_LOGIN_EMAIL=satish@fincuro.9on.in
      - REACT_APP_FORMIO_LOGIN_PASSWORD=Satish@123456
    depends_on:
      - finx-loan-officer

  fincuro-customer:
    build: ./fincuro-customer-loan-app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - REACT_APP_FORMIO_API_BASE_URL=http://3.110.81.211
      - REACT_APP_FORMIO_LOGIN_EMAIL=satish@fincuro.9on.in
      - REACT_APP_FORMIO_LOGIN_PASSWORD=Satish@123456
    depends_on:
      - fincuro-loan-officer

  fincuro-loan-officer:
    build: ./fincuro-loan-officer-app
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production